# Server
server.port=9898
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# Database Config (Supabase / PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&currentSchema=auth_schema
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10

# Cloud Kafka (Upstash / Confluent)
spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.properties.security.protocol=SASL_SSL
spring.kafka.producer.properties.sasl.mechanism=PLAIN
spring.kafka.producer.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.retries=3
spring.kafka.producer.properties.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.nit.serializer.UserInfoSerializer
spring.kafka.topic-json.name=${KAFKA_TOPIC:user_service}
spring.kafka.producer.properties.spring.json.type.mapping=auth:authservice.model.UserInfoEvent

# Security Defaults
security.basic.enable=false
security.ignored=/**

spring.kafka.properties.ssl.truststore.location=app/src/main/resources/ca.pem
spring.kafka.properties.ssl.truststore.type=PEM

